// ╔══════════════════════════════════════════════════════════════════╗
//  📚 BIBLIOTHÈQUE DE CARTES — AJOUTEZ VOS CARTES ICI
//
//  ► Pour ajouter une carte, copiez le bloc modèle ci-dessous
//    et collez-le AVANT le commentaire "FIN DE LA BIBLIOTHÈQUE".
//
//  ► Chaque carte doit avoir un `id` UNIQUE (incrémentez juste +1).
//
//  ► Déposez l'image dans le dossier  images/  de votre GitHub.
//    Formats acceptés : .webp  .webp  .webp
//
//  ═══════════════ MODÈLE À COPIER ════════════════════════════════
//  {
//    id: 99,                          // ← ID unique, incrémentez
//    word: 'Le Mot',                  // ← Mot avec article
//    phonetic: '/lə mɔ/',             // ← Phonétique IPA
//    translation: 'The Word',         // ← Traduction anglaise
//    category: 'Catégorie',           // ← Nom de catégorie libre
//    image: 'images/mot.webp',         // ← Chemin image GitHub
//    emoji: '📝',                     // ← Emoji fallback si pas d'image
//    accent: '#00e5ff',               // ← Couleur accent (#hex)
//    example: 'Phrase exemple courte.',
//    definition: 'Définition courte.',
//    bonus: {
//      def: 'Définition longue et détaillée.',
//      example: 'Exemple avec <em>mot mis en valeur</em>.',
//      tags: ['synonyme1', 'synonyme2', 'mot-lié'],
//      grammar: 'Note grammaticale : genre, pluriel, usage.',
//    },
//  },
//  ════════════════════════════════════════════════════════════════
// ╚══════════════════════════════════════════════════════════════════╝

const CARDS = [
  {
    id: 1,
    word: 'La Maison',
    phonetic: '/la mɛ.zɔ̃/',
    translation: 'The House',
    category: 'Habitation',
    image: 'images/maison.webp',
    emoji: '🏠',
    accent: '#00e5ff',
    example: 'Ma maison est grande et lumineuse.',
    definition: 'Bâtiment servant de lieu d\'habitation à une ou plusieurs personnes ou familles.',
    bonus: {
      def: 'Bâtiment servant de lieu d\'habitation à une ou plusieurs personnes. Par extension, désigne aussi le foyer familial et le sentiment de chez-soi.',
      example: '<em>Ma maison</em> est grande et lumineuse — j\'y vis depuis dix ans.',
      tags: ['appartement', 'logement', 'foyer', 'demeure', 'résidence'],
      grammar: 'Nom féminin (la/une maison). Pluriel : les maisons. Adjectif associé : maison·nel·le.',
    },
  },
  {
    id: 2,
    word: 'Le Chat',
    phonetic: '/lə ʃa/',
    translation: 'The Cat',
    category: 'Animaux',
    image: 'images/chat.webp',
    emoji: '🐱',
    accent: '#ff2d78',
    example: 'Le chat dort sur le canapé.',
    definition: 'Petit mammifère carnivore domestique, au pelage doux et aux mœurs indépendantes.',
    bonus: {
      def: 'Petit mammifère carnivore (Felis catus) domestiqué depuis l\'Égypte ancienne. Animal indépendant et affectueux, symbole de mystère dans de nombreuses cultures.',
      example: '<em>Le chat</em> dort sur le canapé — il a chassé des souris toute la nuit.',
      tags: ['chaton', 'félin', 'ronronner', 'miauler', 'griffes'],
      grammar: 'Nom masculin (le/un chat). Féminin : la chatte. Pluriel : les chats. Verbe associé : miauler.',
    },
  },
  {
    id: 3,
    word: 'La Forêt',
    phonetic: '/la fɔ.ʁɛ/',
    translation: 'The Forest',
    category: 'Nature',
    image: 'images/foret.webp',
    emoji: '🌲',
    accent: '#00f5a0',
    example: 'Nous nous promenons dans la forêt en automne.',
    definition: 'Grande étendue de terrain couverte d\'arbres et de végétation dense.',
    bonus: {
      def: 'Vaste étendue de terrain où poussent des arbres en densité élevée. La forêt abrite une biodiversité exceptionnelle et joue un rôle crucial dans la régulation du climat.',
      example: 'Nous nous promenons dans <em>la forêt</em> en automne — les feuilles sont dorées.',
      tags: ['bois', 'arbres', 'nature', 'randonnée', 'biodiversité', 'sylviculture'],
      grammar: 'Nom féminin (la/une forêt). Pluriel : les forêts. Adjectif : forestier·ère.',
    },
  },
  {
    id: 4,
    word: 'La Voiture',
    phonetic: '/la vwa.tyʁ/',
    translation: 'The Car',
    category: 'Transport',
    image: 'images/voiture.webp',
    emoji: '🚗',
    accent: '#ffb700',
    example: 'Il conduit sa voiture tous les matins.',
    definition: 'Véhicule automobile à quatre roues destiné au transport de personnes.',
    bonus: {
      def: 'Véhicule automobile à moteur thermique ou électrique, à quatre roues, destiné au transport de personnes. Symbole de liberté et de mobilité individuelle.',
      example: 'Il conduit <em>sa voiture</em> tous les matins pour aller au travail.',
      tags: ['automobile', 'conduire', 'permis', 'moteur', 'route', 'garage'],
      grammar: 'Nom féminin (la/une voiture). Pluriel : les voitures. Verbe associé : conduire.',
    },
  },
  {
    id: 5,
    word: 'Le Pain',
    phonetic: '/lə pɛ̃/',
    translation: 'The Bread',
    category: 'Nourriture',
    image: 'images/pain.webp',
    emoji: '🥖',
    accent: '#ff6b35',
    example: 'J\'achète du pain frais chaque matin à la boulangerie.',
    definition: 'Aliment de base fait de farine, d\'eau, de sel et de levure, cuit au four.',
    bonus: {
      def: 'Aliment fondamental de la cuisine française, fait de farine, d\'eau, de sel et de levure boulangère. La baguette est le symbole du pain français, inscrite au patrimoine culturel immatériel de l\'UNESCO.',
      example: 'J\'achète du <em>pain frais</em> chaque matin à la boulangerie du quartier.',
      tags: ['baguette', 'farine', 'boulanger', 'croûte', 'mie', 'levure'],
      grammar: 'Nom masculin (le/du pain). Article partitif : du pain. Pluriel : des pains (pour les variétés).',
    },
  },
  {
    id: 6,
    word: 'Le Soleil',
    phonetic: '/lə sɔ.lɛj/',
    translation: 'The Sun',
    category: 'Nature',
    image: 'images/soleil.webp',
    emoji: '☀️',
    accent: '#ffb700',
    example: 'Le soleil se couche à l\'horizon en été.',
    definition: 'Étoile centrale de notre système solaire, source de lumière et de chaleur.',
    bonus: {
      def: 'Étoile naine jaune (type G2V) au centre de notre système solaire. Source de toute vie sur Terre grâce à l\'énergie lumineuse et thermique qu\'elle produit.',
      example: '<em>Le soleil</em> se couche à l\'horizon en été, teintant le ciel d\'orange.',
      tags: ['lumière', 'chaleur', 'étoile', 'ciel', 'été', 'rayons', 'astronomie'],
      grammar: 'Nom masculin (le soleil). Généralement employé sans article indéfini. Adjectif : solaire.',
    },
  },
  {
    id: 7,
    word: 'Le Livre',
    phonetic: '/lə livʁ/',
    translation: 'The Book',
    category: 'Culture',
    image: 'images/livre.webp',
    emoji: '📚',
    accent: '#9b5de5',
    example: 'Elle lit un livre passionnant sur l\'histoire de France.',
    definition: 'Ensemble de pages imprimées ou manuscrites reliées ensemble, formant un ouvrage.',
    bonus: {
      def: 'Assemblage de pages imprimées ou manuscrites, reliées entre elles, constituant un ouvrage littéraire, scientifique ou artistique. La France est l\'un des plus grands pays producteurs de livres au monde.',
      example: 'Elle lit <em>un livre passionnant</em> sur l\'histoire de France depuis trois jours.',
      tags: ['lire', 'lecture', 'roman', 'auteur', 'bibliothèque', 'librairie'],
      grammar: 'Nom masculin (le/un livre). Pluriel : les livres. Ne pas confondre avec "la livre" (unité de mesure).',
    },
  },
  {
    id: 8,
    word: 'La Mer',
    phonetic: '/la mɛʁ/',
    translation: 'The Sea',
    category: 'Nature',
    image: 'images/mer.webp',
    emoji: '🌊',
    accent: '#00e5ff',
    example: 'Nous nageons dans la mer chaude en juillet.',
    definition: 'Grande étendue d\'eau salée, moins vaste que l\'océan, bordant les terres.',
    bonus: {
      def: 'Étendue d\'eau salée plus petite qu\'un océan, bordée de terres. La France bénéficie d\'un accès à deux mers (Méditerranée) et deux océans (Atlantique, Manche).',
      example: 'Nous nageons dans <em>la mer</em> chaude en juillet — l\'eau est à 27 degrés.',
      tags: ['vagues', 'plage', 'côte', 'marée', 'horizon', 'navigation', 'océan'],
      grammar: 'Nom féminin (la/une mer). Pluriel : les mers. Adjectif : marin·e, maritime. Homophones : mère, maire.',
    },
  },
  {
    id: 9,
    word: 'L\'Oiseau',
    phonetic: '/lwa.zo/',
    translation: 'The Bird',
    category: 'Animaux',
    image: 'images/oiseau.webp',
    emoji: '🐦',
    accent: '#00f5a0',
    example: 'L\'oiseau chante dans l\'arbre au lever du soleil.',
    definition: 'Animal vertébré à plumes, pourvu d\'ailes et d\'un bec, généralement apte au vol.',
    bonus: {
      def: 'Animal vertébré tétrapode à corps couvert de plumes, muni d\'un bec et de deux ailes. La plupart volent, mais certains sont terrestres (autruche, manchot). Il existe environ 10 000 espèces dans le monde.',
      example: '<em>L\'oiseau</em> chante dans l\'arbre au lever du soleil — c\'est un merle.',
      tags: ['plumes', 'voler', 'nid', 'chanter', 'bec', 'plumage', 'migration'],
      grammar: 'Nom masculin (l\'/un oiseau). Pluriel : les oiseaux. L\'apostrophe est obligatoire devant "oiseau" car commence par une voyelle.',
    },
  },
  {
    id: 10,
    word: 'La Cuisine',
    phonetic: '/la kɥi.zin/',
    translation: 'The Kitchen / Cooking',
    category: 'Habitation',
    image: 'images/cuisine.webp',
    emoji: '🍳',
    accent: '#ff6b35',
    example: 'La cuisine française est réputée dans le monde entier.',
    definition: 'Pièce de la maison où l\'on prépare les repas ; aussi l\'art de préparer les aliments.',
    bonus: {
      def: 'Double sens : (1) pièce d\'une habitation équipée pour préparer les aliments ; (2) art et manière de préparer et cuisiner les aliments. La cuisine française est inscrite au patrimoine immatériel de l\'UNESCO.',
      example: '<em>La cuisine française</em> est réputée dans le monde entier pour sa finesse.',
      tags: ['cuisiner', 'chef', 'recette', 'gastronomie', 'casserole', 'four', 'fourneaux'],
      grammar: 'Nom féminin (la/une cuisine). Pluriel : les cuisines. Verbe associé : cuisiner. Double sens à connaître !',
    },
  },
  {
    id: 11,
    word: 'Le Vélo',
    phonetic: '/lə ve.lo/',
    translation: 'The Bicycle',
    category: 'Transport',
    image: 'images/velo.webp',
    emoji: '🚲',
    accent: '#ff2d78',
    example: 'Je fais du vélo chaque dimanche matin dans le parc.',
    definition: 'Véhicule à deux roues propulsé par des pédales, sans moteur.',
    bonus: {
      def: 'Abréviation de vélocipède. Véhicule à deux roues propulsé par la force musculaire via des pédales. Mode de transport écologique très populaire en France, notamment à Paris avec le système Vélib\'.',
      example: 'Je fais du <em>vélo</em> chaque dimanche matin dans le parc de la ville.',
      tags: ['pédaler', 'cyclisme', 'roue', 'selle', 'guidon', 'piste cyclable'],
      grammar: 'Nom masculin (le/un vélo). Pluriel : les vélos. Expression : "faire du vélo" (utiliser un vélo).',
    },
  },
  {
    id: 12,
    word: 'La Fleur',
    phonetic: '/la flœʁ/',
    translation: 'The Flower',
    category: 'Nature',
    image: 'images/fleur.webp',
    emoji: '🌸',
    accent: '#ff2d78',
    example: 'Il offre des fleurs à sa mère pour la fête des mères.',
    definition: 'Organe reproducteur des plantes à fleurs, souvent coloré et parfumé.',
    bonus: {
      def: 'Structure reproductive colorée des plantes angiospermes, attirant les pollinisateurs. En français, "fleur" est aussi utilisé dans de nombreuses expressions idiomatiques liées à la beauté et à la délicatesse.',
      example: 'Il offre des <em>fleurs fraîches</em> à sa mère pour la fête des mères.',
      tags: ['pétale', 'parfum', 'bouquet', 'jardin', 'floraison', 'pollinisation'],
      grammar: 'Nom féminin (la/une fleur). Pluriel : les fleurs. Expressions : "dans la fleur de l\'âge", "faire une fleur à quelqu\'un".',
    },
  },
  {
  id: 13,
  word: 'Le Chien',
  phonetic: '/lə ʃjɛ̃/',
  translation: 'The Dog',
  category: 'Animaux',
  image: 'images/chien.webp',
  emoji: '🐶',
  accent: '#ff9f1c',
  example: 'Le chien garde la maison.',
  definition: 'Animal domestique fidèle, souvent utilisé comme compagnon ou gardien.',
  bonus: {
    def: 'Mammifère carnivore domestique (Canis lupus familiaris), connu pour sa loyauté envers l\'homme.',
    example: '<em>Le chien</em> garde la maison toute la nuit.',
    tags: ['chiot', 'aboyer', 'fidèle', 'compagnon', 'laisse'],
    grammar: 'Nom masculin (le/un chien). Féminin : la chienne. Pluriel : les chiens.',
  },
},
{
  id: 14,
  word: 'Le Cheval',
  phonetic: '/lə ʃə.val/',
  translation: 'The Horse',
  category: 'Animaux',
  image: 'images/cheval.webp',
  emoji: '🐴',
  accent: '#8d6e63',
  example: 'Le cheval court dans le champ.',
  definition: 'Grand mammifère herbivore utilisé pour le transport ou le sport.',
  bonus: {
    def: 'Animal domestique utilisé depuis des siècles pour le transport, l\'agriculture et les loisirs.',
    example: '<em>Le cheval</em> court librement dans le champ.',
    tags: ['équitation', 'galop', 'crinière', 'selle'],
    grammar: 'Nom masculin (le/un cheval). Pluriel : les chevaux.',
  },
},
{
  id: 15,
  word: 'Le Lion',
  phonetic: '/lə ljɔ̃/',
  translation: 'The Lion',
  category: 'Animaux',
  image: 'images/lion.webp',
  emoji: '🦁',
  accent: '#f4a261',
  example: 'Le lion rugit dans la savane.',
  definition: 'Grand félin carnivore, souvent appelé le roi des animaux.',
  bonus: {
    def: 'Félin sauvage vivant principalement en Afrique, connu pour sa crinière et sa puissance.',
    example: '<em>Le lion</em> rugit au coucher du soleil.',
    tags: ['savane', 'roi', 'rugir', 'prédateur'],
    grammar: 'Nom masculin (le/un lion). Féminin : la lionne. Pluriel : les lions.',
  },
},
{
  id: 16,
  word: 'Le Poisson',
  phonetic: '/lə pwa.sɔ̃/',
  translation: 'The Fish',
  category: 'Animaux',
  image: 'images/poisson.webp',
  emoji: '🐟',
  accent: '#00b4d8',
  example: 'Le poisson nage dans l\'eau.',
  definition: 'Animal aquatique vivant dans l\'eau et respirant par des branchies.',
  bonus: {
    def: 'Vertébré aquatique à sang froid, respirant par des branchies.',
    example: '<em>Le poisson</em> nage rapidement dans l\'aquarium.',
    tags: ['eau', 'nage', 'branchies', 'océan'],
    grammar: 'Nom masculin (le/un poisson). Pluriel : les poissons.',
  },
},
{
  id: 17,
  word: 'Le Lapin',
  phonetic: '/lə la.pɛ̃/',
  translation: 'The Rabbit',
  category: 'Animaux',
  image: 'images/lapin.webp',
  emoji: '🐰',
  accent: '#f1c0e8',
  example: 'Le lapin mange une carotte.',
  definition: 'Petit mammifère herbivore aux longues oreilles.',
  bonus: {
    def: 'Animal rapide et timide, souvent domestiqué ou vivant à l\'état sauvage.',
    example: '<em>Le lapin</em> saute dans le jardin.',
    tags: ['oreilles', 'carotte', 'sauter', 'terrier'],
    grammar: 'Nom masculin (le/un lapin). Pluriel : les lapins.',
  },
},
{
  id: 18,
  word: 'La Vache',
  phonetic: '/la vaʃ/',
  translation: 'The Cow',
  category: 'Animaux',
  image: 'images/vache.webp',
  emoji: '🐄',
  accent: '#90be6d',
  example: 'La vache produit du lait.',
  definition: 'Mammifère herbivore domestique élevé pour le lait et la viande.',
  bonus: {
    def: 'Animal d\'élevage essentiel dans l\'agriculture.',
    example: '<em>La vache</em> broute dans le pré.',
    tags: ['lait', 'ferme', 'brouter', 'élevage'],
    grammar: 'Nom féminin (la/une vache). Pluriel : les vaches.',
  },
},
{
  id: 19,
  word: 'Le Cochon',
  phonetic: '/lə kɔ.ʃɔ̃/',
  translation: 'The Pig',
  category: 'Animaux',
  image: 'images/cochon.webp',
  emoji: '🐷',
  accent: '#ff99c8',
  example: 'Le cochon vit dans la ferme.',
  definition: 'Animal domestique élevé pour sa viande.',
  bonus: {
    def: 'Mammifère omnivore connu pour son intelligence.',
    example: '<em>Le cochon</em> joue dans la boue.',
    tags: ['ferme', 'boue', 'porc'],
    grammar: 'Nom masculin (le/un cochon). Pluriel : les cochons.',
  },
},
{
  id: 20,
  word: 'Le Mouton',
  phonetic: '/lə mu.tɔ̃/',
  translation: 'The Sheep',
  category: 'Animaux',
  image: 'images/mouton.webp',
  emoji: '🐑',
  accent: '#e9edc9',
  example: 'Le mouton a de la laine.',
  definition: 'Animal domestique élevé pour sa laine et sa viande.',
  bonus: {
    def: 'Herbivore vivant souvent en troupeau.',
    example: '<em>Le mouton</em> suit le troupeau.',
    tags: ['laine', 'troupeau', 'berger'],
    grammar: 'Nom masculin (le/un mouton). Pluriel : les moutons.',
  },
},
{
  id: 21,
  word: 'La Poule',
  phonetic: '/la pul/',
  translation: 'The Hen',
  category: 'Animaux',
  image: 'images/poule.webp',
  emoji: '🐔',
  accent: '#ffd166',
  example: 'La poule pond des œufs.',
  definition: 'Oiseau domestique élevé pour ses œufs.',
  bonus: {
    def: 'Animal de basse-cour très courant.',
    example: '<em>La poule</em> picore dans la cour.',
    tags: ['œuf', 'ferme', 'coq'],
    grammar: 'Nom féminin (la/une poule). Pluriel : les poules.',
  },
},
{
  id: 22,
  word: 'Le Canard',
  phonetic: '/lə ka.naʁ/',
  translation: 'The Duck',
  category: 'Animaux',
  image: 'images/canard.webp',
  emoji: '🦆',
  accent: '#a0c4ff',
  example: 'Le canard nage sur le lac.',
  definition: 'Oiseau aquatique au bec large.',
  bonus: {
    def: 'Oiseau vivant près de l\'eau, souvent domestiqué.',
    example: '<em>Le canard</em> plonge dans l\'eau.',
    tags: ['lac', 'plumes', 'nager'],
    grammar: 'Nom masculin (le/un canard). Pluriel : les canards.',
  },
},
{
  id: 23,
  word: 'Le Serpent',
  phonetic: '/lə sɛʁ.pɑ̃/',
  translation: 'The Snake',
  category: 'Animaux',
  image: 'images/serpent.webp',
  emoji: '🐍',
  accent: '#588157',
  example: 'Le serpent rampe sur le sol.',
  definition: 'Reptile sans pattes au corps allongé.',
  bonus: {
    def: 'Reptile carnivore pouvant être venimeux.',
    example: '<em>Le serpent</em> se cache dans l\'herbe.',
    tags: ['reptile', 'venin', 'ramper'],
    grammar: 'Nom masculin (le/un serpent). Pluriel : les serpents.',
  },
},
{
  id: 24,
  word: 'Le Singe',
  phonetic: '/lə sɛ̃ʒ/',
  translation: 'The Monkey',
  category: 'Animaux',
  image: 'images/singe.webp',
  emoji: '🐒',
  accent: '#c77dff',
  example: 'Le singe grimpe dans les arbres.',
  definition: 'Mammifère intelligent proche de l\'homme.',
  bonus: {
    def: 'Primate vivant dans les forêts tropicales.',
    example: '<em>Le singe</em> mange une banane.',
    tags: ['banane', 'forêt', 'grimpe'],
    grammar: 'Nom masculin (le/un singe). Pluriel : les singes.',
  },
},
{
  id: 25,
  word: 'Le Fromage',
  phonetic: '/lə fʁɔ.maʒ/',
  translation: 'The Cheese',
  category: 'Nourriture',
  image: 'images/fromage.webp',
  emoji: '🧀',
  accent: '#ffd166',
  example: 'Le fromage français est célèbre.',
  definition: 'Produit laitier obtenu par coagulation du lait.',
  bonus: {
    def: 'Aliment typique de la gastronomie française, décliné en centaines de variétés.',
    example: '<em>Le fromage</em> est servi après le plat principal.',
    tags: ['lait', 'camembert', 'brie', 'goût'],
    grammar: 'Nom masculin (le/un fromage). Pluriel : les fromages.',
  },
},
{
  id: 26,
  word: 'La Pomme',
  phonetic: '/la pɔm/',
  translation: 'The Apple',
  category: 'Nourriture',
  image: 'images/pomme.webp',
  emoji: '🍎',
  accent: '#e63946',
  example: 'Je mange une pomme.',
  definition: 'Fruit rond et sucré ou acidulé.',
  bonus: {
    def: 'Fruit très consommé dans le monde, riche en fibres.',
    example: 'Je mange <em>une pomme</em> chaque matin.',
    tags: ['fruit', 'sucré', 'croquant'],
    grammar: 'Nom féminin (la/une pomme). Pluriel : les pommes.',
  },
},
{
  id: 27,
  word: 'Le Croissant',
  phonetic: '/lə kʁwa.sɑ̃/',
  translation: 'The Croissant',
  category: 'Nourriture',
  image: 'images/croissant.webp',
  emoji: '🥐',
  accent: '#f4a261',
  example: 'Je mange un croissant au petit-déjeuner.',
  definition: 'Viennoiserie en forme de lune, feuilletée et beurrée.',
  bonus: {
    def: 'Spécialité française très populaire au petit-déjeuner.',
    example: 'Je prends <em>un croissant</em> avec un café.',
    tags: ['boulangerie', 'beurre', 'petit-déjeuner'],
    grammar: 'Nom masculin (le/un croissant). Pluriel : les croissants.',
  },
},
{
  id: 28,
  word: 'La Pizza',
  phonetic: '/la pit.sa/',
  translation: 'The Pizza',
  category: 'Nourriture',
  image: 'images/pizza.webp',
  emoji: '🍕',
  accent: '#ff6b35',
  example: 'Nous partageons une pizza.',
  definition: 'Plat d’origine italienne avec pâte, sauce tomate et garniture.',
  bonus: {
    def: 'Plat populaire dans le monde entier.',
    example: 'Nous mangeons <em>une pizza</em> entre amis.',
    tags: ['fromage', 'tomate', 'four'],
    grammar: 'Nom féminin (la/une pizza). Pluriel : les pizzas.',
  },
},
{
  id: 29,
  word: 'La Salade',
  phonetic: '/la sa.lad/',
  translation: 'The Salad',
  category: 'Nourriture',
  image: 'images/salade.webp',
  emoji: '🥗',
  accent: '#80ed99',
  example: 'Je prépare une salade fraîche.',
  definition: 'Mélange de légumes crus ou cuits.',
  bonus: {
    def: 'Plat léger souvent consommé en entrée.',
    example: '<em>La salade</em> est très fraîche.',
    tags: ['légumes', 'sain', 'entrée'],
    grammar: 'Nom féminin (la/une salade). Pluriel : les salades.',
  },
},
{
  id: 30,
  word: 'Le Steak',
  phonetic: '/lə stɛk/',
  translation: 'The Steak',
  category: 'Nourriture',
  image: 'images/steak.webp',
  emoji: '🥩',
  accent: '#9d0208',
  example: 'Il mange un steak.',
  definition: 'Tranche de viande grillée.',
  bonus: {
    def: 'Viande de bœuf souvent grillée ou poêlée.',
    example: 'Il commande <em>un steak</em> au restaurant.',
    tags: ['viande', 'grillade'],
    grammar: 'Nom masculin (le/un steak). Pluriel : les steaks.',
  },
},
{
  id: 31,
  word: 'Le Riz',
  phonetic: '/lə ʁi/',
  translation: 'The Rice',
  category: 'Nourriture',
  image: 'images/riz.webp',
  emoji: '🍚',
  accent: '#f1faee',
  example: 'Je mange du riz.',
  definition: 'Céréale très consommée dans le monde.',
  bonus: {
    def: 'Aliment de base en Asie et dans de nombreux pays.',
    example: 'Je prépare <em>du riz</em> pour le dîner.',
    tags: ['céréale', 'blanc', 'plat'],
    grammar: 'Nom masculin (du riz). Invariable au pluriel.',
  },
},
{
  id: 32,
  word: 'Le Gâteau',
  phonetic: '/lə ɡa.to/',
  translation: 'The Cake',
  category: 'Nourriture',
  image: 'images/gateau.webp',
  emoji: '🎂',
  accent: '#ffafcc',
  example: 'Le gâteau est délicieux.',
  definition: 'Dessert sucré cuit au four.',
  bonus: {
    def: 'Dessert servi lors des fêtes et anniversaires.',
    example: '<em>Le gâteau</em> est au chocolat.',
    tags: ['dessert', 'sucré', 'anniversaire'],
    grammar: 'Nom masculin (le/un gâteau). Pluriel : les gâteaux.',
  },
},
{
  id: 33,
  word: 'Le Chocolat',
  phonetic: '/lə ʃɔ.kɔ.la/',
  translation: 'The Chocolate',
  category: 'Nourriture',
  image: 'images/chocolat.webp',
  emoji: '🍫',
  accent: '#6f4e37',
  example: 'J’aime le chocolat.',
  definition: 'Produit sucré à base de cacao.',
  bonus: {
    def: 'Aliment apprécié dans le monde entier.',
    example: 'Je mange <em>du chocolat</em> le soir.',
    tags: ['cacao', 'sucré'],
    grammar: 'Nom masculin (le/du chocolat).',
  },
},
{
  id: 34,
  word: 'Le Café',
  phonetic: '/lə ka.fe/',
  translation: 'The Coffee',
  category: 'Nourriture',
  image: 'images/cafe.webp',
  emoji: '☕',
  accent: '#6d4c41',
  example: 'Je bois un café.',
  definition: 'Boisson stimulante à base de grains torréfiés.',
  bonus: {
    def: 'Boisson très consommée en France.',
    example: 'Je prends <em>un café</em> le matin.',
    tags: ['boisson', 'énergie'],
    grammar: 'Nom masculin (le/un café).',
  },
},
{
  id: 35,
  word: 'L’Eau',
  phonetic: '/lo/',
  translation: 'The Water',
  category: 'Nourriture',
  image: 'images/eau.webp',
  emoji: '💧',
  accent: '#00b4d8',
  example: 'Je bois de l’eau.',
  definition: 'Liquide essentiel à la vie.',
  bonus: {
    def: 'Indispensable pour le corps humain.',
    example: 'Je bois <em>de l’eau</em> toute la journée.',
    tags: ['boisson', 'vie'],
    grammar: 'Nom féminin (l’eau).',
  },
},
{
  id: 36,
  word: 'La Bière',
  phonetic: '/la bjɛʁ/',
  translation: 'The Beer',
  category: 'Nourriture',
  image: 'images/biere.webp',
  emoji: '🍺',
  accent: '#ffb703',
  example: 'Il boit une bière.',
  definition: 'Boisson alcoolisée à base de céréales.',
  bonus: {
    def: 'Boisson fermentée populaire.',
    example: 'Il commande <em>une bière</em>.',
    tags: ['alcool', 'boisson'],
    grammar: 'Nom féminin (la/une bière).',
  },
},
{
  id: 37,
  word: 'La Soupe',
  phonetic: '/la sup/',
  translation: 'The Soup',
  category: 'Nourriture',
  image: 'images/soupe.webp',
  emoji: '🍲',
  accent: '#fcbf49',
  example: 'Je mange de la soupe.',
  definition: 'Préparation liquide chaude.',
  bonus: {
    def: 'Plat souvent consommé en hiver.',
    example: 'Je mange <em>de la soupe</em> le soir.',
    tags: ['chaud', 'légumes'],
    grammar: 'Nom féminin (la/une soupe).',
  },
},
{
  id: 38,
  word: 'Le Sandwich',
  phonetic: '/lə sɑ̃.dwitʃ/',
  translation: 'The Sandwich',
  category: 'Nourriture',
  image: 'images/sandwich.webp',
  emoji: '🥪',
  accent: '#adb5bd',
  example: 'Je mange un sandwich.',
  definition: 'Pain garni d’aliments variés.',
  bonus: {
    def: 'Repas rapide et pratique.',
    example: 'Je prends <em>un sandwich</em> à midi.',
    tags: ['rapide', 'pain'],
    grammar: 'Nom masculin (le/un sandwich). Pluriel : les sandwiches.',
  },
},
{
  id: 39,
  word: 'La Glace',
  phonetic: '/la ɡlas/',
  translation: 'The Ice Cream',
  category: 'Nourriture',
  image: 'images/glace.webp',
  emoji: '🍦',
  accent: '#bde0fe',
  example: 'Je mange une glace.',
  definition: 'Dessert froid sucré.',
  bonus: {
    def: 'Très populaire en été.',
    example: 'Je mange <em>une glace</em> à la vanille.',
    tags: ['dessert', 'froid'],
    grammar: 'Nom féminin (la/une glace).',
  },
},
{
  id: 40,
  word: 'Le Bus',
  phonetic: '/lə bys/',
  translation: 'The Bus',
  category: 'Transport',
  image: 'images/bus.webp',
  emoji: '🚌',
  accent: '#00b4d8',
  example: 'Je prends le bus pour aller au travail.',
  definition: 'Véhicule de transport en commun circulant sur la route.',
  bonus: {
    def: 'Moyen de transport public utilisé en ville et en zone rurale.',
    example: 'Je prends <em>le bus</em> tous les matins.',
    tags: ['transport public', 'arrêt', 'passager', 'ticket'],
    grammar: 'Nom masculin (le/un bus). Pluriel : les bus.',
  },
},
{
  id: 41,
  word: 'Le Train',
  phonetic: '/lə tʁɛ̃/',
  translation: 'The Train',
  category: 'Transport',
  image: 'images/train.webp',
  emoji: '🚆',
  accent: '#9b5de5',
  example: 'Le train arrive à la gare.',
  definition: 'Moyen de transport ferroviaire circulant sur des rails.',
  bonus: {
    def: 'Transport rapide reliant différentes villes.',
    example: '<em>Le train</em> part à 8 heures.',
    tags: ['gare', 'rail', 'voyage', 'TGV'],
    grammar: 'Nom masculin (le/un train). Pluriel : les trains.',
  },
},
{
  id: 42,
  word: 'L’Avion',
  phonetic: '/la.vjɔ̃/',
  translation: 'The Airplane',
  category: 'Transport',
  image: 'images/avion.webp',
  emoji: '✈️',
  accent: '#00e5ff',
  example: 'L’avion décolle dans une heure.',
  definition: 'Appareil volant permettant de transporter des passagers dans les airs.',
  bonus: {
    def: 'Moyen de transport aérien utilisé pour les longues distances.',
    example: '<em>L’avion</em> traverse l’océan.',
    tags: ['aéroport', 'vol', 'pilote', 'voyage'],
    grammar: 'Nom masculin (l’/un avion). Pluriel : les avions.',
  },
},
{
  id: 43,
  word: 'Le Métro',
  phonetic: '/lə me.tʁo/',
  translation: 'The Subway',
  category: 'Transport',
  image: 'images/metro.webp',
  emoji: '🚇',
  accent: '#ff2d78',
  example: 'Je prends le métro à Paris.',
  definition: 'Train urbain circulant généralement sous terre.',
  bonus: {
    def: 'Transport rapide dans les grandes villes.',
    example: 'Je prends <em>le métro</em> tous les jours.',
    tags: ['station', 'ligne', 'ticket', 'ville'],
    grammar: 'Nom masculin (le/un métro). Pluriel : les métros.',
  },
},
{
  id: 44,
  word: 'Le Taxi',
  phonetic: '/lə tak.si/',
  translation: 'The Taxi',
  category: 'Transport',
  image: 'images/taxi.webp',
  emoji: '🚕',
  accent: '#ffb700',
  example: 'Je prends un taxi pour aller à l’aéroport.',
  definition: 'Véhicule avec chauffeur que l’on peut louer pour un trajet.',
  bonus: {
    def: 'Transport individuel souvent utilisé en ville.',
    example: 'Je prends <em>un taxi</em> le soir.',
    tags: ['chauffeur', 'course', 'ville'],
    grammar: 'Nom masculin (le/un taxi). Pluriel : les taxis.',
  },
},
{
  id: 45,
  word: 'Le Camion',
  phonetic: '/lə ka.mjɔ̃/',
  translation: 'The Truck',
  category: 'Transport',
  image: 'images/camion.webp',
  emoji: '🚚',
  accent: '#8d99ae',
  example: 'Le camion transporte des marchandises.',
  definition: 'Véhicule lourd utilisé pour transporter des objets.',
  bonus: {
    def: 'Utilisé pour le transport de marchandises sur route.',
    example: '<em>Le camion</em> livre les colis.',
    tags: ['livraison', 'marchandise', 'route'],
    grammar: 'Nom masculin (le/un camion). Pluriel : les camions.',
  },
},
{
  id: 46,
  word: 'Le Bateau',
  phonetic: '/lə ba.to/',
  translation: 'The Boat',
  category: 'Transport',
  image: 'images/bateau.webp',
  emoji: '⛵',
  accent: '#00f5a0',
  example: 'Le bateau traverse la mer.',
  definition: 'Moyen de transport flottant sur l’eau.',
  bonus: {
    def: 'Utilisé pour voyager ou transporter des marchandises sur l’eau.',
    example: '<em>Le bateau</em> part du port.',
    tags: ['mer', 'port', 'navigation'],
    grammar: 'Nom masculin (le/un bateau). Pluriel : les bateaux.',
  },
},
{
  id: 47,
  word: 'Le Tramway',
  phonetic: '/lə tʁam.wɛ/',
  translation: 'The Tram',
  category: 'Transport',
  image: 'images/tramway.webp',
  emoji: '🚊',
  accent: '#06d6a0',
  example: 'Le tramway circule en centre-ville.',
  definition: 'Transport urbain circulant sur des rails en ville.',
  bonus: {
    def: 'Alternative écologique au bus.',
    example: 'Je prends <em>le tramway</em> pour aller au centre.',
    tags: ['ville', 'rail', 'transport public'],
    grammar: 'Nom masculin (le/un tramway). Pluriel : les tramways.',
  },
},
{
  id: 48,
  word: 'Le Musée',
  phonetic: '/lə my.ze/',
  translation: 'The Museum',
  category: 'Culture',
  image: 'images/musee.webp',
  emoji: '🏛️',
  accent: '#9b5de5',
  example: 'Nous visitons le musée du Louvre à Paris.',
  definition: 'Établissement qui conserve et expose des œuvres d\'art ou des objets historiques.',
  bonus: {
    def: 'Institution culturelle chargée de collecter, conserver et exposer des œuvres d\'art, des objets historiques ou scientifiques. La France possède certains des musées les plus visités au monde, dont le Louvre.',
    example: 'Nous visitons <em>le musée</em> du Louvre — il abrite la Joconde.',
    tags: ['exposition', 'art', 'histoire', 'collection', 'patrimoine', 'visite'],
    grammar: 'Nom masculin (le/un musée). Pluriel : les musées. Adjectif : muséal·e.',
  },
},
{
  id: 49,
  word: 'Le Théâtre',
  phonetic: '/lə te.ɑtʁ/',
  translation: 'The Theatre',
  category: 'Culture',
  image: 'images/theatre.webp',
  emoji: '🎭',
  accent: '#ff2d78',
  example: 'Elle joue dans une pièce de théâtre ce soir.',
  definition: 'Art de la scène mettant en jeu des acteurs devant un public ; lieu où se jouent des pièces.',
  bonus: {
    def: 'Art vivant où des comédiens interprètent des textes dramatiques devant un public. Aussi le lieu où se déroulent ces représentations. La tradition théâtrale française remonte à Molière au XVIIe siècle.',
    example: 'Elle joue dans <em>une pièce de théâtre</em> ce soir — c\'est Molière.',
    tags: ['scène', 'acteur', 'pièce', 'comédie', 'tragédie', 'représentation', 'Molière'],
    grammar: 'Nom masculin (le/un théâtre). Pluriel : les théâtres. Adjectif : théâtral·e.',
  },
},
{
  id: 50,
  word: 'La Peinture',
  phonetic: '/la pɛ̃.tyʁ/',
  translation: 'The Painting',
  category: 'Culture',
  image: 'images/peinture.webp',
  emoji: '🎨',
  accent: '#ffb700',
  example: 'Cette peinture date du XVIIe siècle.',
  definition: 'Art de représenter des formes et des couleurs sur une surface ; œuvre ainsi produite.',
  bonus: {
    def: 'Art plastique consistant à appliquer des pigments sur une surface pour créer des images ou des compositions. Désigne aussi bien la pratique que l\'œuvre produite. La France a vu naître de nombreux grands courants picturaux.',
    example: '<em>Cette peinture</em> date du XVIIe siècle — c\'est un chef-d\'œuvre du baroque.',
    tags: ['tableau', 'toile', 'peintre', 'couleur', 'pinceau', 'aquarelle', 'huile'],
    grammar: 'Nom féminin (la/une peinture). Pluriel : les peintures. Verbe associé : peindre.',
  },
},
{
  id: 51,
  word: 'La Sculpture',
  phonetic: '/la skylp.tyʁ/',
  translation: 'The Sculpture',
  category: 'Culture',
  image: 'images/sculpture.webp',
  emoji: '🗿',
  accent: '#8d99ae',
  example: 'La sculpture de Rodin est exposée au musée.',
  definition: 'Art de créer des formes en volume à partir de matériaux comme la pierre, le bois ou le métal.',
  bonus: {
    def: 'Art plastique en trois dimensions, consistant à tailler, modeler ou assembler des matériaux pour créer des œuvres en volume. Auguste Rodin est l\'un des sculpteurs français les plus célèbres.',
    example: '<em>La sculpture</em> de Rodin est exposée au musée d\'Orsay.',
    tags: ['marbre', 'bronze', 'sculpteur', 'modelage', 'volume', 'statue', 'Rodin'],
    grammar: 'Nom féminin (la/une sculpture). Pluriel : les sculptures. Verbe associé : sculpter.',
  },
},
{
  id: 52,
  word: 'La Musique',
  phonetic: '/la my.zik/',
  translation: 'The Music',
  category: 'Culture',
  image: 'images/musique.webp',
  emoji: '🎵',
  accent: '#00e5ff',
  example: 'La musique classique me détend après une longue journée.',
  definition: 'Art d\'organiser sons et silences dans le temps pour créer une œuvre artistique.',
  bonus: {
    def: 'Art consistant à combiner des sons selon des règles harmoniques et rythmiques. La France a contribué à de nombreux genres musicaux, de la chanson française à l\'électro, en passant par la musique classique.',
    example: '<em>La musique</em> classique me détend — j\'écoute Debussy.',
    tags: ['mélodie', 'rythme', 'instrument', 'harmonie', 'chanson', 'compositeur', 'concert'],
    grammar: 'Nom féminin (la/une musique). Pluriel : les musiques. Adjectif : musical·e.',
  },
},
{
  id: 53,
  word: 'Le Cinéma',
  phonetic: '/lə si.ne.ma/',
  translation: 'The Cinema',
  category: 'Culture',
  image: 'images/cinema.webp',
  emoji: '🎬',
  accent: '#ff6b35',
  example: 'Nous allons au cinéma voir un film français ce soir.',
  definition: 'Art de créer des films ; lieu où l\'on projette des films.',
  bonus: {
    def: 'Septième art, inventé par les frères Lumière à Lyon en 1895. Désigne à la fois l\'art de réaliser des films et les salles de projection. La France est l\'un des pays les plus importants de l\'histoire du cinéma mondial.',
    example: 'Nous allons <em>au cinéma</em> voir un film de la Nouvelle Vague.',
    tags: ['film', 'réalisateur', 'acteur', 'salle', 'projection', 'Lumière', 'Cannes'],
    grammar: 'Nom masculin (le/un cinéma). Pluriel : les cinémas. Adjectif : cinématographique.',
  },
},
{
  id: 54,
  word: 'La Danse',
  phonetic: '/la dɑ̃s/',
  translation: 'The Dance',
  category: 'Culture',
  image: 'images/danse.webp',
  emoji: '💃',
  accent: '#ff2d78',
  example: 'Elle prend des cours de danse classique depuis l\'enfance.',
  definition: 'Art du mouvement du corps en rythme, souvent accompagné de musique.',
  bonus: {
    def: 'Art vivant exprimant des émotions à travers des mouvements corporels rhythmés. La France est mondialement reconnue pour son excellence en danse classique, notamment grâce à l\'Opéra de Paris.',
    example: 'Elle prend des cours de <em>danse classique</em> depuis l\'enfance — elle rêve de l\'Opéra.',
    tags: ['ballet', 'chorégraphie', 'danseur', 'scène', 'rythme', 'mouvement', 'Opéra'],
    grammar: 'Nom féminin (la/une danse). Pluriel : les danses. Verbe associé : danser.',
  },
},
{
  id: 55,
  word: 'La Langue',
  phonetic: '/la lɑ̃ɡ/',
  translation: 'The Language',
  category: 'Culture',
  image: 'images/langue.webp',
  emoji: '🗣️',
  accent: '#00f5a0',
  example: 'Le français est une langue parlée sur cinq continents.',
  definition: 'Système de signes verbaux propre à une communauté humaine, permettant la communication.',
  bonus: {
    def: 'Système structuré de communication verbale propre à un groupe humain. Le français est la langue officielle de 29 pays et est parlé par environ 320 millions de personnes dans le monde.',
    example: '<em>Le français</em> est une langue parlée sur cinq continents — c\'est la langue de Molière.',
    tags: ['parler', 'grammaire', 'vocabulaire', 'francophonie', 'dialecte', 'accent', 'linguistique'],
    grammar: 'Nom féminin (la/une langue). Pluriel : les langues. Ne pas confondre avec "la langue" (organe buccal).',
  },
},
{
  id: 56,
  word: 'L\'Architecture',
  phonetic: '/laʁ.ʃi.tɛk.tyʁ/',
  translation: 'The Architecture',
  category: 'Culture',
  image: 'images/architecture.webp',
  emoji: '🏗️',
  accent: '#9b5de5',
  example: 'L\'architecture gothique des cathédrales françaises est impressionnante.',
  definition: 'Art et technique de concevoir et construire des bâtiments.',
  bonus: {
    def: 'Art et discipline scientifique visant à concevoir et réaliser des édifices fonctionnels et esthétiques. La France est riche d\'un patrimoine architectural exceptionnel, du roman au contemporain.',
    example: '<em>L\'architecture gothique</em> des cathédrales françaises est impressionnante.',
    tags: ['bâtiment', 'façade', 'style', 'gothique', 'baroque', 'patrimoine', 'architecte'],
    grammar: 'Nom féminin (l\'/une architecture). Pluriel : les architectures. Adjectif : architectural·e.',
  },
},
{
  id: 57,
  word: 'La Photographie',
  phonetic: '/la fɔ.tɔ.ɡʁa.fi/',
  translation: 'The Photography',
  category: 'Culture',
  image: 'images/photographie.webp',
  emoji: '📷',
  accent: '#00e5ff',
  example: 'La photographie noir et blanc capture l\'essence du moment.',
  definition: 'Art et technique de capturer des images à l\'aide d\'un appareil photo.',
  bonus: {
    def: 'Technique et art de fixer des images par l\'action de la lumière sur une surface sensible. Inventée par Niépce et Daguerre en France au XIXe siècle, elle est aujourd\'hui un art à part entière.',
    example: '<em>La photographie</em> noir et blanc capture l\'essence du moment — une image vaut mille mots.',
    tags: ['appareil', 'cliché', 'objectif', 'lumière', 'portrait', 'paysage', 'Daguerre'],
    grammar: 'Nom féminin (la/une photographie). Abréviation courante : la photo. Verbe associé : photographier.',
  },
},
{
  id: 58,
  word: 'La Littérature',
  phonetic: '/la li.te.ʁa.tyʁ/',
  translation: 'The Literature',
  category: 'Culture',
  image: 'images/litterature.webp',
  emoji: '✍️',
  accent: '#ff6b35',
  example: 'La littérature française a produit de nombreux Prix Nobel.',
  definition: 'Ensemble des œuvres écrites d\'une langue ou d\'une époque, considérées dans leur valeur artistique.',
  bonus: {
    def: 'Ensemble des productions écrites reconnues pour leur valeur esthétique et leur portée culturelle. La France est l\'un des pays les plus couronnés au Prix Nobel de Littérature, avec des auteurs comme Camus, Sartre et Le Clézio.',
    example: '<em>La littérature française</em> a produit de nombreux Prix Nobel — Camus, Sartre, Modiano.',
    tags: ['roman', 'poésie', 'écrivain', 'auteur', 'récit', 'Prix Nobel', 'Camus'],
    grammar: 'Nom féminin (la/une littérature). Pluriel rare : les littératures (selon les langues). Adjectif : littéraire.',
  },
},
{
  id: 59,
  word: 'Le Patrimoine',
  phonetic: '/lə pa.tʁi.mwan/',
  translation: 'The Heritage',
  category: 'Culture',
  image: 'images/patrimoine.webp',
  emoji: '🏰',
  accent: '#ffb700',
  example: 'Le patrimoine historique de la France attire des millions de touristes.',
  definition: 'Ensemble des biens, matériels ou immatériels, transmis par les générations passées.',
  bonus: {
    def: 'Ensemble des biens culturels, naturels et historiques légués par les générations précédentes. La France compte parmi les pays les plus riches en sites classés au patrimoine mondial de l\'UNESCO.',
    example: '<em>Le patrimoine historique</em> de la France attire des millions de touristes chaque année.',
    tags: ['UNESCO', 'monument', 'histoire', 'tradition', 'conservation', 'héritage', 'château'],
    grammar: 'Nom masculin (le/un patrimoine). Pluriel : les patrimoines. Adjectif : patrimonial·e.',
  },
},
{
  id: 60,
  word: 'La Mode',
  phonetic: '/la mɔd/',
  translation: 'The Fashion',
  category: 'Culture',
  image: 'images/mode.webp',
  emoji: '👗',
  accent: '#ff2d78',
  example: 'Paris est la capitale mondiale de la mode.',
  definition: 'Art de créer et porter des vêtements selon les tendances d\'une époque.',
  bonus: {
    def: 'Ensemble des tendances vestimentaires et esthétiques d\'une époque donnée. Paris est depuis le XVIIe siècle la capitale mondiale de la mode, avec des maisons de couture légendaires comme Chanel, Dior ou Louis Vuitton.',
    example: '<em>Paris</em> est la capitale mondiale de la mode — la Fashion Week y attire le monde entier.',
    tags: ['couture', 'styliste', 'tendance', 'défilé', 'Chanel', 'Dior', 'élégance'],
    grammar: 'Nom féminin (la/une mode). Pluriel : les modes. Adjectif : à la mode (expression figée).',
  },
},
{
  id: 61,
  word: 'La Gastronomie',
  phonetic: '/la ɡas.tʁɔ.nɔ.mi/',
  translation: 'The Gastronomy',
  category: 'Culture',
  image: 'images/gastronomie.webp',
  emoji: '🍽️',
  accent: '#ff6b35',
  example: 'La gastronomie française est inscrite au patrimoine de l\'UNESCO.',
  definition: 'Art de bien manger et de préparer des mets raffinés ; étude de la cuisine comme pratique culturelle.',
  bonus: {
    def: 'Connaissance et art de tout ce qui se rapporte à la cuisine et au bien manger. La gastronomie française, inscrite en 2010 au patrimoine culturel immatériel de l\'UNESCO, est une véritable institution culturelle.',
    example: '<em>La gastronomie française</em> est inscrite à l\'UNESCO — elle incarne un art de vivre.',
    tags: ['chef', 'recette', 'terroir', 'étoile Michelin', 'saveur', 'raffinement', 'cuisine'],
    grammar: 'Nom féminin (la gastronomie). Généralement sans pluriel. Adjectif : gastronomique.',
  },
},
{
  id: 62,
  word: 'Le Festival',
  phonetic: '/lə fɛs.ti.val/',
  translation: 'The Festival',
  category: 'Culture',
  image: 'images/festival.webp',
  emoji: '🎪',
  accent: '#00f5a0',
  example: 'Le Festival de Cannes réunit les plus grands cinéastes du monde.',
  definition: 'Manifestation culturelle ou artistique périodique regroupant spectacles, concerts ou projections.',
  bonus: {
    def: 'Événement culturel de grande envergure réunissant artistes et public autour d\'un thème ou d\'une discipline. La France est terre de festivals, du Festival de Cannes à Avignon en passant par les Francofolies.',
    example: '<em>Le Festival</em> de Cannes réunit les plus grands cinéastes — la Palme d\'or est très convoitée.',
    tags: ['Cannes', 'Avignon', 'spectacle', 'concert', 'artiste', 'palmarès', 'événement'],
    grammar: 'Nom masculin (le/un festival). Pluriel : les festivals.',
  },
},
{
  id: 63,
  word: 'La Poésie',
  phonetic: '/la pɔ.e.zi/',
  translation: 'The Poetry',
  category: 'Culture',
  image: 'images/poesie.webp',
  emoji: '📝',
  accent: '#9b5de5',
  example: 'La poésie de Victor Hugo a marqué toute la littérature française.',
  definition: 'Art d\'évoquer émotions et images par le langage rythmé et imagé.',
  bonus: {
    def: 'Forme d\'expression littéraire jouant sur le rythme, les sonorités et les images pour susciter des émotions. La France a produit des poètes majeurs comme Hugo, Baudelaire, Rimbaud et Apollinaire.',
    example: '<em>La poésie</em> de Victor Hugo a marqué toute la littérature française — "Les Misérables" en est l\'écho.',
    tags: ['vers', 'rime', 'strophe', 'Hugo', 'Baudelaire', 'Rimbaud', 'métaphore'],
    grammar: 'Nom féminin (la/une poésie). Pluriel : les poésies. Adjectif : poétique. Auteur : le/la poète.',
  },
},
{
  id: 64,
  word: 'L\'Opéra',
  phonetic: '/lɔ.pe.ʁa/',
  translation: 'The Opera',
  category: 'Culture',
  image: 'images/opera.webp',
  emoji: '🎼',
  accent: '#ff2d78',
  example: 'L\'Opéra Garnier est l\'un des plus beaux bâtiments de Paris.',
  definition: 'Œuvre musicale scénique mêlant chant, orchestre et mise en scène ; lieu où l\'on joue ces œuvres.',
  bonus: {
    def: 'Genre musical dramatique associant chant, musique d\'orchestre, décors et jeu d\'acteurs. L\'Opéra Garnier de Paris, inauguré en 1875, est un chef-d\'œuvre architectural et l\'une des institutions culturelles les plus prestigieuses au monde.',
    example: '<em>L\'Opéra Garnier</em> est l\'un des plus beaux bâtiments de Paris — le Fantôme y rôde.',
    tags: ['chant', 'orchestre', 'soprano', 'ténor', 'Garnier', 'aria', 'mise en scène'],
    grammar: 'Nom masculin (l\'/un opéra). Pluriel : les opéras. Adjectif : lyrique (art lyrique = opéra).',
  },
},
{
  id: 65,
  word: 'La Bibliothèque',
  phonetic: '/la bib.ljɔ.tɛk/',
  translation: 'The Library',
  category: 'Culture',
  image: 'images/bibliotheque.webp',
  emoji: '📚',
  accent: '#00e5ff',
  example: 'La Bibliothèque nationale de France conserve des millions de documents.',
  definition: 'Lieu où sont rassemblés et mis à disposition des livres et documents.',
  bonus: {
    def: 'Établissement public ou privé qui collecte, conserve et met à disposition des ouvrages et documents. La Bibliothèque nationale de France (BnF) est l\'une des plus grandes et des plus anciennes bibliothèques du monde.',
    example: '<em>La Bibliothèque nationale de France</em> conserve des millions de documents — dont des manuscrits médiévaux.',
    tags: ['lecture', 'livre', 'document', 'BnF', 'archive', 'emprunt', 'catalogue'],
    grammar: 'Nom féminin (la/une bibliothèque). Pluriel : les bibliothèques. Ne pas confondre avec "la librairie" (bookshop).',
  },
},
{
  id: 66,
  word: 'La Banane',
  phonetic: '/la ba.nan/',
  translation: 'The Banana',
  category: 'Fruits',
  image: 'images/banane.webp',
  emoji: '🍌',
  accent: '#ffd60a',
  example: 'Je mange une banane au petit-déjeuner.',
  definition: 'Fruit allongé à la peau jaune, à la chair sucrée et molle.',
  bonus: {
    def: 'Fruit tropical riche en potassium, poussant en régimes sur le bananier. Très consommé en France malgré son origine exotique, notamment grâce à la production des Antilles françaises.',
    example: 'Je mange <em>une banane</em> au petit-déjeuner pour faire le plein d\'énergie.',
    tags: ['tropical', 'potassium', 'bananier', 'jaune', 'sucré'],
    grammar: 'Nom féminin (la/une banane). Pluriel : les bananes.',
  },
},
{
  id: 67,
  word: 'L\'Orange',
  phonetic: '/lɔ.ʁɑ̃ʒ/',
  translation: 'The Orange',
  category: 'Fruits',
  image: 'images/orange.webp',
  emoji: '🍊',
  accent: '#ff9f1c',
  example: 'Je presse une orange chaque matin pour le jus.',
  definition: 'Agrume rond à la peau orange, juteux et légèrement acidulé.',
  bonus: {
    def: 'Agrume riche en vitamine C, cultivé principalement dans les régions méditerranéennes. Le mot a donné son nom à la couleur orange en français.',
    example: 'Je presse <em>une orange</em> chaque matin pour le petit-déjeuner.',
    tags: ['agrume', 'vitamine C', 'jus', 'acidulé', 'Méditerranée'],
    grammar: 'Nom féminin (l\'/une orange). Pluriel : les oranges. Aussi adjectif de couleur (invariable).',
  },
},
{
  id: 68,
  word: 'La Fraise',
  phonetic: '/la fʁɛz/',
  translation: 'The Strawberry',
  category: 'Fruits',
  image: 'images/fraise.webp',
  emoji: '🍓',
  accent: '#e63946',
  example: 'Les fraises de mai sont particulièrement sucrées.',
  definition: 'Petit fruit rouge, juteux et sucré, couvert de minuscules graines.',
  bonus: {
    def: 'Faux-fruit rouge issu du fraisier, très apprécié au printemps. La France est l\'un des grands producteurs européens, notamment grâce à des variétés comme la gariguette.',
    example: '<em>Les fraises</em> de mai sont particulièrement sucrées et parfumées.',
    tags: ['printemps', 'rouge', 'sucré', 'fraisier', 'gariguette'],
    grammar: 'Nom féminin (la/une fraise). Pluriel : les fraises.',
  },
},
{
  id: 69,
  word: 'Le Raisin',
  phonetic: '/lə ʁɛ.zɛ̃/',
  translation: 'The Grape',
  category: 'Fruits',
  image: 'images/raisin.webp',
  emoji: '🍇',
  accent: '#7209b7',
  example: 'Nous mangeons du raisin après le dîner.',
  definition: 'Petit fruit rond poussant en grappes, utilisé aussi pour faire du vin.',
  bonus: {
    def: 'Fruit de la vigne, consommé frais ou transformé en vin, raisins secs ou jus. La viticulture française fait du raisin un fruit emblématique du terroir national.',
    example: 'Nous mangeons <em>du raisin</em> après le dîner, en dessert.',
    tags: ['vigne', 'grappe', 'vin', 'vendange', 'terroir'],
    grammar: 'Nom masculin (le/du raisin). Pluriel rare : les raisins (pour les variétés).',
  },
},
{
  id: 70,
  word: 'La Poire',
  phonetic: '/la pwaʁ/',
  translation: 'The Pear',
  category: 'Fruits',
  image: 'images/poire.webp',
  emoji: '🍐',
  accent: '#a7c957',
  example: 'Cette poire est bien mûre et juteuse.',
  definition: 'Fruit allongé à la base renflée, à la chair fondante et sucrée.',
  bonus: {
    def: 'Fruit du poirier, à la chair fondante, souvent consommé frais ou en compote. La poire Williams est l\'une des variétés les plus appréciées en France.',
    example: '<em>Cette poire</em> est bien mûre et juteuse, parfaite à croquer.',
    tags: ['poirier', 'fondant', 'compote', 'Williams'],
    grammar: 'Nom féminin (la/une poire). Pluriel : les poires.',
  },
},
{
  id: 71,
  word: 'Le Citron',
  phonetic: '/lə si.tʁɔ̃/',
  translation: 'The Lemon',
  category: 'Fruits',
  image: 'images/citron.webp',
  emoji: '🍋',
  accent: '#ffea00',
  example: 'J\'ajoute du jus de citron dans ma salade.',
  definition: 'Agrume jaune, très acide, utilisé en cuisine et dans les boissons.',
  bonus: {
    def: 'Agrume très acide à la peau jaune, riche en vitamine C. Indispensable en cuisine française pour assaisonner poissons, salades et desserts.',
    example: 'J\'ajoute du <em>jus de citron</em> dans ma salade pour relever le goût.',
    tags: ['agrume', 'acide', 'zeste', 'vitamine C', 'assaisonnement'],
    grammar: 'Nom masculin (le/un citron). Pluriel : les citrons. Adjectif : citronné·e.',
  },
},
{
  id: 72,
  word: 'La Pêche',
  phonetic: '/la pɛʃ/',
  translation: 'The Peach',
  category: 'Fruits',
  image: 'images/peche.webp',
  emoji: '🍑',
  accent: '#ffb4a2',
  example: 'La pêche d\'été a une peau veloutée.',
  definition: 'Fruit rond à la peau duveteuse et à la chair juteuse, souvent jaune ou blanche.',
  bonus: {
    def: 'Fruit d\'été à noyau, à la peau duveteuse et à la chair très juteuse. Très cultivée dans le sud de la France, notamment dans la vallée du Rhône.',
    example: '<em>La pêche</em> d\'été a une peau veloutée et un parfum sucré.',
    tags: ['été', 'duveteux', 'noyau', 'Rhône', 'juteux'],
    grammar: 'Nom féminin (la/une pêche). Pluriel : les pêches. Homonyme : la pêche (activité de pêcher).',
  },
},
{
  id: 73,
  word: 'L\'Ananas',
  phonetic: '/a.na.nas/',
  translation: 'The Pineapple',
  category: 'Fruits',
  image: 'images/ananas.webp',
  emoji: '🍍',
  accent: '#f4d35e',
  example: 'L\'ananas frais est meilleur que l\'ananas en boîte.',
  definition: 'Gros fruit tropical à la peau écailleuse et au sommet feuillu, à la chair sucrée et acidulée.',
  bonus: {
    def: 'Fruit tropical reconnaissable à sa peau écailleuse et son panache de feuilles. Symbole d\'exotisme, il est souvent associé aux Antilles françaises et à la cuisine créole.',
    example: '<em>L\'ananas frais</em> est meilleur que l\'ananas en boîte, plus parfumé.',
    tags: ['tropical', 'exotique', 'créole', 'Antilles', 'sucré'],
    grammar: 'Nom masculin (l\'/un ananas). Invariable au pluriel : les ananas.',
  },
},
{
  id: 74,
  word: 'La Cerise',
  phonetic: '/la sə.ʁiz/',
  translation: 'The Cherry',
  category: 'Fruits',
  image: 'images/cerise.webp',
  emoji: '🍒',
  accent: '#d00000',
  example: 'Les enfants adorent cueillir des cerises au printemps.',
  definition: 'Petit fruit rond et rouge à noyau, sucré ou légèrement acidulé.',
  bonus: {
    def: 'Petit fruit à noyau du cerisier, récolté au début de l\'été. L\'expression "la cerise sur le gâteau" désigne en français un détail final qui rend une chose parfaite.',
    example: 'Les enfants adorent cueillir des <em>cerises</em> au printemps dans le verger.',
    tags: ['cerisier', 'noyau', 'verger', 'rouge', 'expression'],
    grammar: 'Nom féminin (la/une cerise). Pluriel : les cerises. Expression : "la cerise sur le gâteau".',
  },
},
{
  id: 75,
  word: 'Le Kiwi',
  phonetic: '/lə ki.wi/',
  translation: 'The Kiwi',
  category: 'Fruits',
  image: 'images/kiwi.webp',
  emoji: '🥝',
  accent: '#80b918',
  example: 'Le kiwi est riche en vitamine C.',
  definition: 'Petit fruit ovale à la peau brune duveteuse et à la chair verte parsemée de graines noires.',
  bonus: {
    def: 'Fruit d\'origine asiatique, aujourd\'hui largement cultivé dans le sud-ouest de la France, notamment dans les Landes, premier producteur français.',
    example: '<em>Le kiwi</em> est riche en vitamine C — plus que l\'orange !',
    tags: ['vitamine C', 'vert', 'Landes', 'duveteux'],
    grammar: 'Nom masculin (le/un kiwi). Pluriel : les kiwis.',
  },
},
{
  id: 76,
  word: 'L\'Abricot',
  phonetic: '/la.bʁi.ko/',
  translation: 'The Apricot',
  category: 'Fruits',
  image: 'images/abricot.webp',
  emoji: '🍑',
  accent: '#ff9e00',
  example: 'L\'abricot mûr se mange en quelques bouchées.',
  definition: 'Petit fruit rond et orangé à noyau, à la chair tendre et parfumée.',
  bonus: {
    def: 'Fruit d\'été à noyau, à la peau veloutée orangée. Très cultivé dans le sud-est de la France, notamment dans la vallée du Rhône et en Provence.',
    example: '<em>L\'abricot</em> mûr se mange en quelques bouchées, juteux à souhait.',
    tags: ['été', 'orange', 'Provence', 'noyau', 'parfumé'],
    grammar: 'Nom masculin (l\'/un abricot). Pluriel : les abricots.',
  },
},
{
  id: 77,
  word: 'Le Melon',
  phonetic: '/lə mə.lɔ̃/',
  translation: 'The Melon',
  category: 'Fruits',
  image: 'images/melon.webp',
  emoji: '🍈',
  accent: '#90be6d',
  example: 'Le melon de Cavaillon est célèbre dans toute la France.',
  definition: 'Gros fruit rond à la chair sucrée et parfumée, souvent orange ou verte.',
  bonus: {
    def: 'Fruit d\'été à la chair sucrée et parfumée, servi traditionnellement en entrée en France. Le melon de Cavaillon, dans le Vaucluse, est réputé pour sa qualité exceptionnelle.',
    example: '<em>Le melon de Cavaillon</em> est célèbre dans toute la France pour sa douceur.',
    tags: ['été', 'Cavaillon', 'entrée', 'sucré', 'Vaucluse'],
    grammar: 'Nom masculin (le/un melon). Pluriel : les melons.',
  },
},
{
  id: 78,
  word: 'La Pastèque',
  phonetic: '/la pas.tɛk/',
  translation: 'The Watermelon',
  category: 'Fruits',
  image: 'images/pasteque.webp',
  emoji: '🍉',
  accent: '#ff4d6d',
  example: 'La pastèque rafraîchit pendant les chaleurs de l\'été.',
  definition: 'Gros fruit rond à l\'écorce verte et à la chair rouge, juteuse et très désaltérante.',
  bonus: {
    def: 'Fruit d\'été composé à plus de 90% d\'eau, très apprécié pour son pouvoir désaltérant lors des fortes chaleurs. Sa chair rouge contraste avec son écorce verte.',
    example: '<em>La pastèque</em> rafraîchit pendant les chaleurs de l\'été — idéale en pique-nique.',
    tags: ['été', 'eau', 'rouge', 'désaltérant', 'rafraîchissant'],
    grammar: 'Nom féminin (la/une pastèque). Pluriel : les pastèques.',
  },
},
{
  id: 79,
  word: 'La Mangue',
  phonetic: '/la mɑ̃ɡ/',
  translation: 'The Mango',
  category: 'Fruits',
  image: 'images/mangue.webp',
  emoji: '🥭',
  accent: '#ff8500',
  example: 'La mangue mûre dégage un parfum sucré et exotique.',
  definition: 'Fruit tropical à noyau, à la chair orange, fondante et parfumée.',
  bonus: {
    def: 'Fruit tropical originaire d\'Asie du Sud, aujourd\'hui répandu dans le monde entier. Sa chair orange et fondante en fait l\'un des fruits exotiques les plus consommés en France.',
    example: '<em>La mangue</em> mûre dégage un parfum sucré et exotique irrésistible.',
    tags: ['tropical', 'exotique', 'orange', 'fondant', 'noyau'],
    grammar: 'Nom féminin (la/une mangue). Pluriel : les mangues.',
  },
},
{
  id: 80,
  word: 'La Framboise',
  phonetic: '/la fʁɑ̃.bwaz/',
  translation: 'The Raspberry',
  category: 'Fruits',
  image: 'images/framboise.webp',
  emoji: '🍇',
  accent: '#e5383b',
  example: 'La tarte aux framboises est un dessert d\'été très apprécié.',
  definition: 'Petit fruit rouge composé de minuscules grains, sucré et légèrement acidulé.',
  bonus: {
    def: 'Petit fruit rouge agrégé, issu du framboisier, très fragile et parfumé. Souvent utilisée en pâtisserie française pour sa couleur vive et son goût acidulé.',
    example: 'La <em>tarte aux framboises</em> est un dessert d\'été très apprécié des Français.',
    tags: ['framboisier', 'rouge', 'pâtisserie', 'acidulé', 'fragile'],
    grammar: 'Nom féminin (la/une framboise). Pluriel : les framboises.',
  },
},
{
  id: 81,
  word: 'La Carotte',
  phonetic: '/la ka.ʁɔt/',
  translation: 'The Carrot',
  category: 'Légumes',
  image: 'images/carotte.webp',
  emoji: '🥕',
  accent: '#ff9f1c',
  example: 'Je coupe les carottes en rondelles pour la soupe.',
  definition: 'Légume racine de couleur orange, croquant et sucré.',
  bonus: {
    def: 'Légume racine très consommé, riche en bêta-carotène, qui lui donne sa couleur orange caractéristique. Présente dans de nombreuses recettes françaises comme les carottes râpées ou le pot-au-feu.',
    example: 'Je coupe <em>les carottes</em> en rondelles pour la soupe du soir.',
    tags: ['racine', 'orange', 'bêta-carotène', 'croquant', 'potager'],
    grammar: 'Nom féminin (la/une carotte). Pluriel : les carottes.',
  },
},
{
  id: 82,
  word: 'La Tomate',
  phonetic: '/la tɔ.mat/',
  translation: 'The Tomato',
  category: 'Légumes',
  image: 'images/tomate.webp',
  emoji: '🍅',
  accent: '#e63946',
  example: 'La tomate est l\'ingrédient principal de la ratatouille.',
  definition: 'Fruit rouge consommé comme légume, juteux et légèrement acidulé.',
  bonus: {
    def: 'Botaniquement un fruit, mais culinairement traité comme un légume. Ingrédient incontournable de la cuisine française et méditerranéenne, notamment dans la ratatouille ou la sauce tomate.',
    example: '<em>La tomate</em> est l\'ingrédient principal de la ratatouille provençale.',
    tags: ['rouge', 'ratatouille', 'sauce', 'potager', 'juteux'],
    grammar: 'Nom féminin (la/une tomate). Pluriel : les tomates.',
  },
},
{
  id: 83,
  word: 'La Pomme de Terre',
  phonetic: '/la pɔm də tɛʁ/',
  translation: 'The Potato',
  category: 'Légumes',
  image: 'images/pommedeterre.webp',
  emoji: '🥔',
  accent: '#d4a373',
  example: 'Nous préparons des pommes de terre sautées pour le dîner.',
  definition: 'Tubercule comestible, base de nombreux plats, pouvant être bouilli, frit ou rôti.',
  bonus: {
    def: 'Tubercule féculent originaire d\'Amérique du Sud, devenu un aliment de base en France depuis le XVIIIe siècle grâce à Parmentier. Se décline en purée, frites, gratin, etc.',
    example: 'Nous préparons des <em>pommes de terre sautées</em> pour accompagner la viande.',
    tags: ['tubercule', 'féculent', 'Parmentier', 'frites', 'purée'],
    grammar: 'Nom féminin composé (la/une pomme de terre). Pluriel : les pommes de terre.',
  },
},
{
  id: 84,
  word: 'L\'Oignon',
  phonetic: '/lɔ.ɲɔ̃/',
  translation: 'The Onion',
  category: 'Légumes',
  image: 'images/oignon.webp',
  emoji: '🧅',
  accent: '#9c6644',
  example: 'L\'oignon fait pleurer quand on le coupe.',
  definition: 'Légume bulbeux au goût piquant, base de nombreuses préparations culinaires.',
  bonus: {
    def: 'Bulbe à saveur piquante, indispensable dans la cuisine française pour parfumer sauces, soupes et plats mijotés. La soupe à l\'oignon est un classique de la gastronomie française.',
    example: '<em>L\'oignon</em> fait pleurer quand on le coupe à cause de ses composés soufrés.',
    tags: ['bulbe', 'piquant', 'soupe', 'sauce', 'condiment'],
    grammar: 'Nom masculin (l\'/un oignon). Pluriel : les oignons.',
  },
},
{
  id: 85,
  word: 'La Salade Verte',
  phonetic: '/la sa.lad vɛʁt/',
  translation: 'The Lettuce',
  category: 'Légumes',
  image: 'images/saladeverte.webp',
  emoji: '🥬',
  accent: '#80ed99',
  example: 'On mange souvent de la salade verte en entrée.',
  definition: 'Plante potagère aux feuilles vertes, consommée crue en accompagnement ou en entrée.',
  bonus: {
    def: 'Légume-feuille très répandu dans la cuisine française, souvent servi en entrée avec une vinaigrette. Il en existe de nombreuses variétés : laitue, batavia, romaine.',
    example: 'On mange souvent <em>de la salade verte</em> en entrée avec une vinaigrette.',
    tags: ['laitue', 'feuille', 'vinaigrette', 'entrée', 'potager'],
    grammar: 'Nom féminin composé (la/une salade verte). Pluriel : les salades vertes. À ne pas confondre avec "la salade" (le plat).',
  },
},
{
  id: 86,
  word: 'Le Poivron',
  phonetic: '/lə pwa.vʁɔ̃/',
  translation: 'The Bell Pepper',
  category: 'Légumes',
  image: 'images/poivron.webp',
  emoji: '🫑',
  accent: '#2d6a4f',
  example: 'Les poivrons rouges sont plus sucrés que les verts.',
  definition: 'Légume creux et coloré, à la chair croquante, utilisé cru ou cuit.',
  bonus: {
    def: 'Légume de la famille des Solanacées, disponible en plusieurs couleurs (vert, rouge, jaune) selon son degré de maturité. Élément essentiel de la ratatouille.',
    example: '<em>Les poivrons rouges</em> sont plus sucrés que les verts, car plus mûrs.',
    tags: ['ratatouille', 'rouge', 'vert', 'croquant', 'Solanacées'],
    grammar: 'Nom masculin (le/un poivron). Pluriel : les poivrons.',
  },
},
{
  id: 87,
  word: 'La Courgette',
  phonetic: '/la kuʁ.ʒɛt/',
  translation: 'The Zucchini',
  category: 'Légumes',
  image: 'images/courgette.webp',
  emoji: '🥒',
  accent: '#52b788',
  example: 'La courgette se cuisine facilement à la poêle ou au four.',
  definition: 'Légume allongé à la peau verte, à la chair tendre et légèrement sucrée.',
  bonus: {
    def: 'Légume d\'été de la famille des cucurbitacées, apprécié pour sa polyvalence en cuisine. Ingrédient clé de la ratatouille provençale.',
    example: '<em>La courgette</em> se cuisine facilement à la poêle ou au four.',
    tags: ['cucurbitacée', 'été', 'ratatouille', 'tendre', 'potager'],
    grammar: 'Nom féminin (la/une courgette). Pluriel : les courgettes.',
  },
},
{
  id: 88,
  word: 'Le Concombre',
  phonetic: '/lə kɔ̃.kɔ̃bʁ/',
  translation: 'The Cucumber',
  category: 'Légumes',
  image: 'images/concombre.webp',
  emoji: '🥒',
  accent: '#74c69d',
  example: 'Je découpe le concombre en fines tranches pour la salade.',
  definition: 'Légume allongé et vert, croquant et riche en eau, souvent consommé cru.',
  bonus: {
    def: 'Légume rafraîchissant composé à plus de 95% d\'eau, très apprécié en salade pendant l\'été. Souvent assaisonné avec de la crème fraîche dans la cuisine française.',
    example: 'Je découpe <em>le concombre</em> en fines tranches pour la salade d\'été.',
    tags: ['croquant', 'eau', 'salade', 'frais', 'été'],
    grammar: 'Nom masculin (le/un concombre). Pluriel : les concombres.',
  },
},
{
  id: 89,
  word: 'L\'Ail',
  phonetic: '/laj/',
  translation: 'The Garlic',
  category: 'Légumes',
  image: 'images/ail.webp',
  emoji: '🧄',
  accent: '#e0e1dd',
  example: 'Une gousse d\'ail parfume parfaitement la sauce tomate.',
  definition: 'Bulbe composé de gousses au goût et à l\'odeur prononcés, utilisé comme condiment.',
  bonus: {
    def: 'Plante bulbeuse de la famille des alliacées, divisée en gousses, utilisée comme condiment dans presque toute la cuisine française et méditerranéenne pour son arôme puissant.',
    example: 'Une <em>gousse d\'ail</em> parfume parfaitement la sauce tomate maison.',
    tags: ['gousse', 'condiment', 'arôme', 'alliacée', 'méditerranée'],
    grammar: 'Nom masculin (l\'/un ail). Pluriel rare : les aulx (ou les ails). Adjectif : aillé·e.',
  },
},
{
  id: 90,
  word: 'Le Brocoli',
  phonetic: '/lə bʁɔ.kɔ.li/',
  translation: 'The Broccoli',
  category: 'Légumes',
  image: 'images/brocoli.webp',
  emoji: '🥦',
  accent: '#2d6a4f',
  example: 'Les enfants n\'aiment pas toujours le brocoli.',
  definition: 'Légume vert composé de petites têtes florales regroupées sur une tige.',
  bonus: {
    def: 'Légume de la famille des Brassicacées, riche en vitamines et fibres. Souvent cuit à la vapeur pour conserver ses qualités nutritionnelles.',
    example: 'Les enfants n\'aiment pas toujours <em>le brocoli</em>, malgré ses bienfaits.',
    tags: ['vert', 'vapeur', 'Brassicacée', 'vitamines', 'fibres'],
    grammar: 'Nom masculin (le/un brocoli). Pluriel : les brocolis.',
  },
},
{
  id: 91,
  word: 'L\'Aubergine',
  phonetic: '/lo.bɛʁ.ʒin/',
  translation: 'The Eggplant',
  category: 'Légumes',
  image: 'images/aubergine.webp',
  emoji: '🍆',
  accent: '#5a189a',
  example: 'L\'aubergine grillée accompagne bien la ratatouille.',
  definition: 'Légume allongé à la peau violette brillante, à la chair tendre une fois cuite.',
  bonus: {
    def: 'Légume de la famille des Solanacées, à la peau violette caractéristique. Indispensable dans la ratatouille et la cuisine méditerranéenne.',
    example: '<em>L\'aubergine grillée</em> accompagne bien la ratatouille provençale.',
    tags: ['violet', 'ratatouille', 'Solanacée', 'méditerranée', 'grillé'],
    grammar: 'Nom féminin (l\'/une aubergine). Pluriel : les aubergines.',
  },
},
{
  id: 92,
  word: 'Le Champignon',
  phonetic: '/lə ʃɑ̃.pi.ɲɔ̃/',
  translation: 'The Mushroom',
  category: 'Légumes',
  image: 'images/champignon.webp',
  emoji: '🍄',
  accent: '#bc6c25',
  example: 'On ramasse des champignons en forêt à l\'automne.',
  definition: 'Organisme sans chlorophylle, souvent consommé comme légume, au chapeau et au pied caractéristiques.',
  bonus: {
    def: 'Bien que biologiquement classé à part, le champignon est cuisiné comme un légume en France. La cueillette des champignons (cèpes, girolles) est une tradition automnale très populaire.',
    example: 'On ramasse des <em>champignons</em> en forêt à l\'automne — surtout des cèpes.',
    tags: ['forêt', 'cueillette', 'automne', 'cèpe', 'girolle'],
    grammar: 'Nom masculin (le/un champignon). Pluriel : les champignons.',
  },
},
{
  id: 93,
  word: 'Le Petit Pois',
  phonetic: '/lə pə.ti pwa/',
  translation: 'The Pea',
  category: 'Légumes',
  image: 'images/petitpois.webp',
  emoji: '🟢',
  accent: '#7cb518',
  example: 'Les petits pois accompagnent souvent le poulet rôti.',
  definition: 'Petite graine ronde et verte, contenue dans une gousse, sucrée et tendre.',
  bonus: {
    def: 'Légumineuse cultivée pour ses petites graines vertes consommées fraîches, surgelées ou en conserve. Plat traditionnel français : "petits pois carottes".',
    example: '<em>Les petits pois</em> accompagnent souvent le poulet rôti du dimanche.',
    tags: ['gousse', 'vert', 'légumineuse', 'tendre', 'sucré'],
    grammar: 'Nom masculin composé (le/un petit pois). Pluriel : les petits pois.',
  },
},
{
  id: 94,
  word: 'Le Poireau',
  phonetic: '/lə pwa.ʁo/',
  translation: 'The Leek',
  category: 'Légumes',
  image: 'images/poireau.webp',
  emoji: '🥬',
  accent: '#588157',
  example: 'La soupe de poireaux est réconfortante en hiver.',
  definition: 'Légume allongé à tige blanche et feuilles vertes, au goût doux proche de l\'oignon.',
  bonus: {
    def: 'Légume de la famille des alliacées, à la saveur douce. Ingrédient classique des soupes et du pot-au-feu dans la cuisine française traditionnelle.',
    example: 'La <em>soupe de poireaux</em> est réconfortante en hiver, souvent avec des pommes de terre.',
    tags: ['soupe', 'pot-au-feu', 'alliacée', 'hiver', 'doux'],
    grammar: 'Nom masculin (le/un poireau). Pluriel : les poireaux.',
  },
},
{
  id: 95,
  word: 'Le Radis',
  phonetic: '/lə ʁa.di/',
  translation: 'The Radish',
  category: 'Légumes',
  image: 'images/radis.webp',
  emoji: '🌶️',
  accent: '#ef233c',
  example: 'On mange des radis avec du beurre et du sel en apéritif.',
  definition: 'Petite racine ronde ou allongée, rouge ou rose, au goût piquant.',
  bonus: {
    def: 'Petit légume racine croquant, souvent servi cru à l\'apéritif en France, traditionnellement accompagné de beurre et d\'une pincée de sel.',
    example: 'On mange des <em>radis</em> avec du beurre et du sel en apéritif.',
    tags: ['racine', 'apéritif', 'beurre', 'croquant', 'piquant'],
    grammar: 'Nom masculin (le/un radis). Pluriel : les radis.',
  },
},
]; // ◄─── FIN DE LA BIBLIOTHÈQUE — ajoutez vos cartes juste au-dessus de cette ligne
